from .heart_disease_model import HeartDiseasePredictor
from .diabetes_model import DiabetesPredictor
from .disease_predictor import DiseasePredictor
from .breast_cancer_model import BreastCancerPredictor
